; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = remyar/YauS-core@^0.0.29
monitor_speed=115200
build_flags = 
	-I$PROJECT_DIR/lib
	-I$PROJECT_DIR/src
	-I$PROJECT_DIR/src/Low-Level
	-I$PROJECT_DIR/src/leds
	-I$PROJECT_DIR/src/motors
